version: '3.8'

services:
  ocdarr-lite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocdarr-lite
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
      - ./data:/app/data
      - ./temp:/app/temp
    ports:
      - "5002:5002"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    
