version: '3.8'
services:
  sonarr_script:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./config:/app/config
      - ./temp:/app/temp
      - ./static:/app/static 
      - ./templates:/app/templates
    ports:
      - "5005:5005"
    restart: unless-stopped
