version: '3.8'
services:
  sonarr_script:
    build:
      context: .
      dockerfile: Dockerfile
    #environment:
      #- REQUESTS_CA_BUNDLE=/usr/local/share/ca-certificates/caddy-root.crt
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./config:/app/config
      - ./temp:/app/temp
      - ./static:/app/static 
      - ./templates:/app/templates
    
    ports:
      - "5002:5002"
    restart: unless-stopped
    network_mode: host
