version: '3'

services:
  episeerr:
    build: .
    container_name: episeerr
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - TZ=UTC
