name: Build and Push to GHCR

on:
  push:
    branches: [ jellyfinwebhook ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract repository name and convert to lowercase
        id: repo-name
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_owner_lowercase=$REPO_OWNER" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.repo-name.outputs.repo_owner_lowercase }}/episeerrjellyfinwebhook:latest
            ghcr.io/${{ steps.repo-name.outputs.repo_owner_lowercase }}/episeerrjellyfinwebhook:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
